/* exemple de phrase pour une recherche au hasard */

export const surpriseMePrompts = [
  "un fauteuil en forme davocat",
  "une peinture à lhuile onirique surréaliste de Salvador Dalí dun chat jouant aux dames",
  "ours en peluche faisant ses courses au Japon",
  "une peinture à lhuile de Matisse représentant un robot humanoïde jouant aux échecs",
  "panda savant fou mélangeant des produits chimiques étincelants, art numérique",
  "une photographie macro 35 mm de deux souris à Hawaï, elles portent chacune de minuscules maillots de bain et portent de minuscules planches de surf, art numérique",
  "Rendu 3D dun joli poisson tropical dans un aquarium sur fond bleu foncé, art numérique",
  "un astronaute se prélassant dans un complexe tropical dans lespace",
  "un portrait de peinture à lhuile dun capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre",
  "un vitrail représentant un hamburger et des frites",
  "un dessin au crayon, une ville lumineuse dans le futur avec des voitures volantes",
  "un salon intérieur ensoleillé avec une piscine à leau claire et une autre piscine à leau rose pastel translucide, à côté dune grande fenêtre, art numérique",
  "un shiba inu qui dit la bonne aventure lisant votre destin dans un hamburger géant, art numérique",
  "une loutre de mer avec une boucle doreille en perles, de Johannes Vermeer",
  "un dessin pastel à lhuile dun chat agacé dans un vaisseau spatial",
  "une peinture dun renard dans le style de Starry Night",
  "un bol de soupe qui ressemble à un monstre, tricoté en laine",
  "Un robot en peluche assis contre un mur jaune",
  "Un coucher de soleil de style synthwave au-dessus de leau réfléchissante de la mer, art numérique",
  "Deux tours futuristes avec une passerelle couverte de feuillage luxuriant, art numérique",
  "Un rendu 3D dun ballon à air chaud de couleur arc-en-ciel volant au-dessus dun lac réfléchissant",
  "Une couverture de bande dessinée dun super-héros portant des écouteurs",
  "Une explosion centrée de poudre colorée sur fond noir",
  "Une photo dun chien Samoyède, la langue tirée, étreignant un chat siamois blanc",
  "Une photo dun monstre à fourrure blanche debout dans une pièce violette",
  "Une photo de la sculpture de Michel-Ange de David portant des écouteurs djing",
  "Un samouraï à cheval sur Mars, lomographie",
  "Une Cadillac moderne et élégante roule le long de lautoroute Gardiner avec le centre-ville de Toronto en arrière-plan, avec une lumière parasite, une photographie de 50 mm",
  "Une photographie réaliste dune jeune femme aux yeux bleus et aux cheveux blonds",
  "Un homme debout devant une porte des étoiles vers une autre dimension",
  "Bob léponge dans le projet blair witch",
  "Un vélociraptor travaillant dans un stand de hot-dogs, lomographie",
  "Un homme marchant dans les rues animées de Kowloon la nuit, éclairé par de nombreuses enseignes lumineuses au néon, objectif 50 mm",
  "Un barbecue vivant, à la manière dun film danimation Pixar",
  "Un club de danse cyborg futuriste, des néons",
  "Une femme avec une perruque rose dans les années 1960",
  "Un hamburger en forme de Rubiks cube, photographie culinaire professionnelle",
  "Un hérisson dans un vaisseau spatial",
  "Un astronaute rencontre une forme de vie extraterrestre sur une planète lointaine, photographie",
  "Un dinosaure explorant Cape Town, photographie",
  "Un homme tombant amoureux de son ordinateur, art numérique",
  "Photographie dxun cyborg explorant Tokyo la nuit, lomographie",
  "Dracula marchant dans la rue de New York dans les années 1920, photographie en noir et blanc",
  "Un avion volant au dessus de paris dans les année 1800",
  "Un homme se promène dans les rues pluvieuses de Tokyo, avec des enseignes lumineuses au néon, 50mm",
  "Une navette spatiale volant au-dessus de Cape Town, art numérique",
];
